### RTLib configuration
### =========================

verbose: true

## Input
## ==========================

input:
  - /path/to/dat/PS061A/evidence.txt
  - /path/to/dat/PS062ABCD/evidence.txt
  - /path/to/dat/PS063/evidence.txt
  - /path/to/dat/PS064AG/evidence.txt

exclude: PS06[1-3][AB]|PS064F

low_memory: false
params_folder: /path/to/output_folder_from_prev_run

## Output
## ==========================

output: /path/to/output/folder
print_figures: true
save_params: true
add_diagnostic_cols: true
overwrite_pep: true

save_combined_output: true
combined_output_name: ev_updated.txt

save_separate_output: true
save_in_input_folder: true
output_suffix: _updated
output_ext: .txt

## Alignment Options
## ==========================

prior_iters: 10
stan_iters: 20000
stan_attempts: 3

mu_min: 1
rt_distortion: 0


## Input Type Options
## ==========================

col_names:

  sequence: Modified sequence
  raw_file: Raw file
  retention_time: Retention time
  pep: PEP

  # optional columns
  leading_protein: Leading razor protein
  proteins: Proteins
  leading_gene: ~
  genes: ~
  retention_length: Retention length
  intensity: Intensity
  exclude: ~
  exp_id: ~
  peptide_id: ~

## Filters
## ==========================

filters:
  - name: uniprot_exclusion
    file: /path/to/list_of_uniprot_ids.txt
    list:
      - or_you_could
      - list_uniprot_ids_here
      - P36578
      - Q99797

  - name: contaminant
    tag: CON__

  - name: decoy
    tag: REV__

  - name: retention_length
    dynamic: true
    value: 0.01667

  - name: pep
    value: 0.5

  - name: smears
    dynamic: true
    value: 0.03333

  - name: num_exps
    value: 3

