### DART-ID configuration
### =========================

verbose: true

## Input
## ==========================

input:
  - /path/to/dat/PS061A/evidence.txt
  - /path/to/dat/PS062ABCD/evidence.txt
  - /path/to/dat/PS063/evidence.txt
  - /path/to/dat/PS064AG/evidence.txt

sep: \t
low_memory: false
params_folder: /path/to/output_folder_from_prev_run

## Alignment Options
## ==========================

model: 'two_piece_linear'

add_charge_to_sequence: false

prior_iters: 10
stan_iters: 20000
stan_attempts: 3

mu_min: 1
rt_distortion: 0

save_stan_input: false

## Update Options
## ==========================

# parametric, non-parametric
bootstrap_method: 'non-parametric'
bootstrap_iters: 50

# mean, median, weighted_mean
mu_estimation: 'median'

## Protein Inference Options
## ==========================

run_pi: false

# optional
pi_gamma: 0.5
pi_alpha: 0.1
pi_beta:  0.01

pi_connected_protein_thresh: 14
pi_clean_peptide_name: false
pi_use_all_psms: false
pi_group_proteins: false
pi_prune_low_scores: true
pi_parameter_accuracy: 3

pi_protein_delimiter: ';'
pi_decoy_tag: 'REV__'

## Output
## ==========================

output: /path/to/output/folder
print_figures: true
save_params: true
add_diagnostic_cols: true
overwrite_pep: true
psm_fdr_threshold: 0.01
protein_fdr_threshold: 0.01

save_combined_output: true
combined_output_name: ev_updated.txt

save_separate_output: true
save_in_input_folder: true
output_suffix: _updated
output_ext: .txt

log_file: true


## Input Type Options
## ==========================

col_names:

  sequence: Modified sequence
  raw_file: Raw file
  retention_time: Retention time
  pep: PEP

  # optional columns
  charge: Charge
  leading_protein: Leading razor protein
  proteins: Proteins
  leading_gene: ~
  genes: ~
  retention_length: Retention length
  intensity: Intensity
  exclude: ~
  exp_id: ~
  peptide_id: ~

## Filters
## ==========================

pep_threshold: 0.5
num_experiments: 3

filters:
  - name: exclude_filename 
    expr: PS06[1-3][AB]|PS064F

  - name: include_filename
    expr: 2018A

  - name: uniprot_exclusion
    file: /path/to/list_of_uniprot_ids.txt
    list:
      - or_you_could
      - list_uniprot_ids_here
      - P36578
      - Q99797

  - name: contaminant
    tag: CON__

  - name: decoy
    tag: REV__

  - name: retention_length
    dynamic: true
    value: 0.01667

  - name: smears
    dynamic: true
    value: 0.03333

