name: dart
channels:
  - defaults
dependencies:
  - python=3.7.6
  - pyyaml=3.12
  - numpy=1.18.1
  - scipy=1.0.0
  - pandas=1.0.1
  - matplotlib=2.1.2
  - networkx=2.1
  - jsonschema=3.0.1
  - pip=19.1
