name: dart
channels:
  - defaults
dependencies:
  - python=3.6.4
  - pyyaml=3.12
#  - pystan=2.17.1.0
  - numpy=1.14.3
  - scipy=1.0.0
  - pandas=0.22.0
  - matplotlib=2.1.2
  - networkx=2.1
  - pip=19.1
  - pip:
    - '--editable=git+https://github.com/blahoink/pystan.git@b6fb404d0a5dd9bd88d85dbcf094b90bd12e3143#egg=pystan'
