### DART-ID configuration - DEFAULTS
### =========================

#input: ~

#output: /path/to/output/folder

print_figures: true

## Input Type Options
## ==========================

col_names:
  sequence: Modified sequence
  raw_file: Raw file
  retention_time: Retention time
  pep: PEP

  # optional columns
  charge: Charge
  leading_protein: Leading razor protein
  proteins: Proteins
  #leading_gene: ~
  #genes: ~
  retention_length: Retention length
  intensity: Intensity
  #exclude: ~
  #exp_id: ~
  #peptide_id: ~

### =======================
### !! ADVANCED SETTINGS !!
### =======================

# Only edit the following settings if you understand their effects
# Please refer to config_annotated.yaml for detailed descriptions for
# each configuration field

verbose: 2

## Input
## ==========================

sep: \t
low_memory: false
#params_folder:

## Alignment Options
## ==========================

model: 'two_piece_linear_laplace'

add_charge_to_sequence: false

prior_iters: 10
stan_iters: 20000

mu_min: 1
rt_distortion: 0

init_alpha: 0.001
tol_obj: 1.e-12
tol_rel_obj: 10000
tol_grad: 1.e-8
tol_rel_grad: 10000000
tol_param: 1.e-8
history_size: 5

## Update Options
## ==========================

# parametric, non-parametric
bootstrap_method: 'parametric_mixture'
bootstrap_iters: 50

# mean, median, weighted_mean
mu_estimation: 'median'

## Protein Inference Options
## ==========================

run_pi: true

# optional
pi_gamma: 0.5
pi_alpha: 0.1
pi_beta:  0.01

pi_connected_protein_thresh: 14
pi_clean_peptide_name: false
pi_use_all_psms: false
pi_group_proteins: false
pi_prune_low_scores: true
pi_parameter_accuracy: 3

pi_protein_delimiter: ';'
pi_decoy_tag: 'REV__'

## Output
## ==========================

save_params: true
add_diagnostic_cols: false
overwrite_pep: false
#psm_fdr_threshold: 0.01
#protein_fdr_threshold: 0.01

save_combined_output: true
combined_output_name: ev_updated.txt

save_separate_output: false
save_in_input_folder: false
output_suffix: _updated
output_ext: .txt

log_file: true

## Filters
## ==========================

pep_threshold: 0.5
num_experiments: 3
min_psms_per_experiment: 50

filters:
  #- name: exclude_filename 
  #  expr: PS06[1-3][AB]|PS064F

  #- name: include_filename
  #  expr: 2018A

  #- name: uniprot_exclusion
  #  file: /path/to/list_of_uniprot_ids.txt
  #  list:
  #    - or_you_could
  #    - list_uniprot_ids_here
  #    - P36578
  #    - Q99797

  #- name: contaminant
  #  tag: CON__

  #- name: decoy
  #  tag: REV__

  #- name: retention_length
  #  dynamic: true
  #  value: 0.01667

  #- name: smears
  #  dynamic: true
  #  value: 0.03333

